// Generated by CoffeeScript 1.3.1
(function() {
  var Gatherer, argv, host, logfile, pidfile, port, usage, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;

  Gatherer = require('./gatherer');

  argv = require('optimist').argv;

  port = (_ref = (_ref1 = argv.p) != null ? _ref1 : argv.port) != null ? _ref : 6379;

  host = (_ref2 = (_ref3 = argv.h) != null ? _ref3 : argv.host) != null ? _ref2 : '10.60.38.98';

  process.title = 'real-time-gath';

  if (argv.help) {
    usage = '\nUsage: real-time-gath --host [host] --port [port]\n\nOptions:\n  -h | --host [optional] * redis connection\n  -p | --port [optional] * redis connection\n\n  -d          (daemonize)\n  --pid <file>\n  --log <file>\n';
    console.log(usage);
  } else {
    if (argv.d) {
      logfile = (_ref4 = argv.log) != null ? _ref4 : '/dev/null';
      pidfile = (_ref5 = argv.pid) != null ? _ref5 : '/var/run/real-time-gath.pid';
      daemon.daemonize(logfile, pidfile, function(err, pid) {
        if (err) {
          return console.log("Error starting daemon: " + err);
        } else {
          console.log("Daemon started successfully with pid: " + pid);
          return new Gatherer(host, port);
        }
      });
    } else {
      new Gatherer(host, port);
    }
  }

}).call(this);
